.TH rexical 1 "May 2015"
.SH NAME
.PP

rexical \- Ruby Lex for Racc
.SH SYNOPSIS
rexical [options] grammarfile
.PP
.SH DESCRIPTION
.PP
Rexical is a lexical scanner generator that is used with Racc to generate Ruby programs.
Rexical is written in Ruby.
.SH OPTIONS
.TP
.fi
.B
\-o, \-\-output-file  filename
designated output filename.
.TP
.fi
.B
\-s, \-\-stub
append stub main for debug.
.TP
.fi
.B
\-i, \-\-ignorecase
ignore char case
.TP
.fi
.B
\-C, \-\-check-only
syntax check only.
.TP
.fi
.B
\-\-independent
independent mode.
.TP
.fi
.B
\-d, \-\-debug
print debug information
.TP
.fi
.B
\-h, \-\-help
print usage.
.TP
.fi
.B
\-\-version
print version.
.TP
.fi
.B
\-\-copyright
print copyright.

.SH SEE ALSO
.PP
/usr/share/doc/rexical/en.html (English)
